In [1]:
#Reshape a 1D array into a 2D array.
import numpy as np
a = np.array([1,2,3,4,5,6])
print(a)
print(a.shape)
print(a.reshape(2,3))
print(a.reshape(2,3).shape)

[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [5]:
#Convert a 2D array into a 1D array.
print(a.reshape(1,6))

[[1 2 3 4 5 6]]


In [7]:
#Transpose a matrix.
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.T)
print(b.T.shape)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [8]:
#Flatten a matrix.
print(b.flatten())
print(b.flatten().shape)

[1 2 3 4 5 6]
(6,)


In [9]:
#Swap the rows and columns of a matrix.
c =np.array([[1,2,3],[4,5,6]])
print(c)
print(c.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
